### ISSUE TITLE
Retrieve documents with where query syntax throws InvalidRequestError

### ISSUE THREAD

**Issue by mayoreee** [dashpay/platform#340] opened 2022-04-12 09:27 UTC
Retrieve documents with `where` query syntax throws InvalidRequestError

## Expected Behavior

Successfully retrieve documents
## Current Behavior

```
Something went wrong:
 InvalidRequestError: Invalid query: Properties in where conditions must be defined as a document index
```

## Steps to Reproduce (for bugs)

Contract's Indices:
```json
"indices": [
      {
        "name": "index",
        "properties": [
          {
            "$ownerId": "asc"
          },
          {
            "$updatedAt": "asc"
          }
        ],
        "unique": false
      }
    ],
```

Query syntax:
```js
           {
                limit: 1, // Only retrieve 1 document
                where: [
                    ['$ownerId', '==', params.ownerId],
                    ['$updatedAt', '==', params.updatedAt]
                ]
            },
```

## Your Environment

* Version used: dash v3.22.1

**Comment by thephez** [comment] 2022-04-12 12:33
Looks similar to #315 so the suggestion in https://github.com/dashevo/platform/issues/315#issuecomment-1085614223 will probably help.

**Comment by SamKirby22** [comment] 2022-04-22 07:49
@mayoreee can you provide link to Github with the complete query - as per todays Triage, this is likely a duplicate of https://github.com/dashevo/platform/issues/315

Further detail required to verify if user error or documentation update required.

**Comment by mayoreee** [comment] 2022-04-22 08:03
@SamKirby22 Not sure about the query you're referring to but the query syntax has been provided in the report above. Could you please help clarify? Thanks.

**Comment by shumkov** [comment] 2024-09-26 11:57
This is outdated.

**Closed by shumkov** 2024-09-26 11:57 UTC
Labels: bug
